import { existsSync, readFileSync, writeFileSync } from "node:fs";

/** Load KEY=VALUE lines into process.env (does not override existing vars). */
export function loadEnvFile(path: string): void {
  if (!existsSync(path)) return;
  for (const line of readFileSync(path, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    const val = trimmed.slice(eq + 1).trim();
    if (key && process.env[key] === undefined) process.env[key] = val;
  }
}

export function writeEnvFile(path: string, vars: Record<string, string | undefined>): void {
  const lines = [
    "# Generated by Pip — do not commit",
    ...Object.entries(vars)
      .filter(([, v]) => v !== undefined && v !== "")
      .map(([k, v]) => `${k}=${v}`),
    "",
  ];
  writeFileSync(path, lines.join("\n"), "utf8");
}
