import { execSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { homedir, platform } from "node:os";
import { dirname, join, resolve } from "node:path";
import { resolveWorkspace } from "@tandem/core";

const LABEL = "com.tandem.bridge";
const LOG_OUT = "/tmp/tandem-bridge.out.log";
const LOG_ERR = "/tmp/tandem-bridge.err.log";

export interface BridgeAutostartStatus {
  installed: boolean;
  plistPath: string;
  envPath: string;
  workspace: string;
  extensionRoot: string;
  runScript: string;
  loaded: boolean;
}

function uid(): string {
  return String(process.getuid?.() ?? execSync("id -u", { encoding: "utf8" }).trim());
}

function plistPath(): string {
  return join(homedir(), "Library", "LaunchAgents", `${LABEL}.plist`);
}

function envPath(): string {
  return join(homedir(), ".tandem", "bridge-autostart.env");
}

function launcherPath(): string {
  return join(homedir(), ".tandem", "launch-bridge.sh");
}

export function findChromeExtensionRoot(cliDir: string): string {
  const fromMonorepo = resolve(cliDir, "../../../apps/chrome-extension");
  if (existsSync(join(fromMonorepo, "bridge", "server.ts"))) return fromMonorepo;

  const workspace = resolveWorkspace(resolve(cliDir, "../../.."));
  const fromWorkspace = join(workspace, "apps", "chrome-extension");
  if (existsSync(join(fromWorkspace, "bridge", "server.ts"))) return fromWorkspace;

  throw new Error(
    "Chrome extension not found. Run from the Pip monorepo (apps/chrome-extension must exist).",
  );
}

function isLaunchAgentLoaded(): boolean {
  try {
    const out = execSync(`launchctl print gui/${uid()}/${LABEL}`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return out.includes("state =");
  } catch {
    return false;
  }
}

export function bridgeAutostartStatus(cliDir: string): BridgeAutostartStatus {
  const extensionRoot = findChromeExtensionRoot(cliDir);
  const runScript = launcherPath();
  const plist = plistPath();
  const env = envPath();
  let workspace = resolveWorkspace(resolve(cliDir, "../../.."));
  if (existsSync(env)) {
    const match = readFileSync(env, "utf8").match(/^TANDEM_WORKSPACE=(.+)$/m);
    if (match?.[1]) workspace = match[1].trim();
  }
  return {
    installed: existsSync(plist),
    plistPath: plist,
    envPath: env,
    workspace,
    extensionRoot,
    runScript,
    loaded: existsSync(plist) && isLaunchAgentLoaded(),
  };
}

function renderLauncher(
  nodeBin: string,
  extensionRoot: string,
  envFile: string,
  serverTs: string,
  workspace: string,
): string {
  return `#!/usr/bin/env bash
# Generated by: tandem bridge autostart install — do not edit by hand.
set -euo pipefail
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
export NVM_DIR="\${NVM_DIR:-$HOME/.nvm}"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  # shellcheck disable=SC1091
  . "$NVM_DIR/nvm.sh"
fi
export TANDEM_WORKSPACE="${workspace}"
cd "${extensionRoot}"
exec "${nodeBin}" --env-file="${envFile}" --import tsx "${serverTs}"
`;
}

function renderPlist(launcher: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${launcher}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${LOG_OUT}</string>
    <key>StandardErrorPath</key>
    <string>${LOG_ERR}</string>
</dict>
</plist>
`;
}

function unloadLaunchAgent(): void {
  const plist = plistPath();
  if (!existsSync(plist)) return;
  try {
    execSync(`launchctl bootout gui/${uid()} "${plist}"`, { stdio: "ignore" });
  } catch {
    try {
      execSync(`launchctl unload "${plist}"`, { stdio: "ignore" });
    } catch {
      // already unloaded
    }
  }
}

function loadLaunchAgent(): void {
  const plist = plistPath();
  execSync(`launchctl bootstrap gui/${uid()} "${plist}"`, { stdio: "inherit" });
}

export function bridgeAutostartInstall(cliDir: string, workspace?: string): BridgeAutostartStatus {
  if (platform() !== "darwin") {
    throw new Error("Login autostart is macOS only.");
  }

  const extensionRoot = findChromeExtensionRoot(cliDir);
  const serverTs = join(extensionRoot, "bridge", "server.ts");
  const envFile = join(extensionRoot, ".env");
  if (!existsSync(serverTs)) throw new Error(`Missing bridge server: ${serverTs}`);
  if (!existsSync(envFile)) {
    const example = join(extensionRoot, ".env.example");
    if (existsSync(example)) {
      writeFileSync(envFile, readFileSync(example, "utf8"), "utf8");
    } else {
      writeFileSync(envFile, "TANDEM_BRIDGE_PORT=8765\nCURSOR_BIN=cursor-agent\n", "utf8");
    }
  }

  const ws = workspace ?? resolveWorkspace(resolve(cliDir, "../../.."));
  mkdirSync(dirname(envPath()), { recursive: true });
  writeFileSync(envPath(), `TANDEM_WORKSPACE=${ws}\n`, "utf8");

  const nodeBin = process.execPath;
  const launcher = launcherPath();
  writeFileSync(launcher, renderLauncher(nodeBin, extensionRoot, envFile, serverTs, ws), "utf8");
  chmodSync(launcher, 0o755);

  mkdirSync(join(homedir(), "Library", "LaunchAgents"), { recursive: true });
  unloadLaunchAgent();
  writeFileSync(plistPath(), renderPlist(launcher), "utf8");
  loadLaunchAgent();

  return bridgeAutostartStatus(cliDir);
}

export function bridgeAutostartUninstall(cliDir: string): void {
  unloadLaunchAgent();
  const plist = plistPath();
  if (existsSync(plist)) unlinkSync(plist);
  const env = envPath();
  if (existsSync(env)) unlinkSync(env);
  const launcher = launcherPath();
  if (existsSync(launcher)) unlinkSync(launcher);
  void cliDir;
}

export function bridgeAutostartUsage(): void {
  console.log(`Usage:
  tandem bridge autostart install    Start the Chrome bridge at login (macOS LaunchAgent)
  tandem bridge autostart uninstall  Remove login autostart
  tandem bridge autostart status     Show autostart state

Logs (when running via autostart):
  ${LOG_OUT}
  ${LOG_ERR}
`);
}
