import { execSync } from "node:child_process";
import { chmodSync, existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { homedir, platform } from "node:os";
import { dirname, join, resolve } from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { resolveWorkspace } from "@tandem/core";

const LABEL = "com.tandem.pip";
const LOG_OUT = "/tmp/tandem-pip.out.log";
const LOG_ERR = "/tmp/tandem-pip.err.log";

export interface PipAutostartStatus {
  installed: boolean;
  plistPath: string;
  envPath: string;
  workspace: string;
  runScript: string;
  loaded: boolean;
}

function uid(): string {
  return String(process.getuid?.() ?? execSync("id -u", { encoding: "utf8" }).trim());
}

function plistPath(): string {
  return join(homedir(), "Library", "LaunchAgents", `${LABEL}.plist`);
}

function envPath(): string {
  return join(homedir(), ".tandem", "autostart.env");
}

export function findPipRoot(cliDir: string): string {
  const require = createRequire(import.meta.url);
  try {
    return dirname(require.resolve("@tandem/pip/package.json"));
  } catch {
    const dev = resolve(cliDir, "../../../apps/pip");
    if (existsSync(join(dev, "package.json"))) return dev;
    throw new Error("@tandem/pip is not installed. Run: npm install -g @tandem/cli @tandem/pip");
  }
}

function isLaunchAgentLoaded(): boolean {
  try {
    const out = execSync(`launchctl print gui/${uid()}/${LABEL}`, {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    return out.includes("state =");
  } catch {
    return false;
  }
}

export function pipAutostartStatus(cliDir: string): PipAutostartStatus {
  const pipRoot = findPipRoot(cliDir);
  const runScript = join(homedir(), ".tandem", "launch-pip.sh");
  const fallbackRunScript = join(pipRoot, "run.sh");
  const plist = plistPath();
  const env = envPath();
  let workspace = resolveWorkspace(resolve(cliDir, "../../.."));
  if (existsSync(env)) {
    const match = readFileSync(env, "utf8").match(/^TANDEM_WORKSPACE=(.+)$/m);
    if (match?.[1]) workspace = match[1].trim();
  }
  return {
    installed: existsSync(plist),
    plistPath: plist,
    envPath: env,
    workspace,
    runScript: existsSync(runScript) ? runScript : fallbackRunScript,
    loaded: existsSync(plist) && isLaunchAgentLoaded(),
  };
}

function renderLauncher(nodeBin: string, pipMjs: string, workspace: string): string {
  return `#!/usr/bin/env bash
# Generated by: tandem pip autostart install — do not edit by hand.
set -euo pipefail
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
export NVM_DIR="\${NVM_DIR:-$HOME/.nvm}"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  # shellcheck disable=SC1091
  . "$NVM_DIR/nvm.sh"
fi
export TANDEM_WORKSPACE="${workspace}"
exec "${nodeBin}" "${pipMjs}"
`;
}

function launcherPath(): string {
  return join(homedir(), ".tandem", "launch-pip.sh");
}

function renderPlist(launcher: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${launcher}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${LOG_OUT}</string>
    <key>StandardErrorPath</key>
    <string>${LOG_ERR}</string>
</dict>
</plist>
`;
}

function unloadLaunchAgent(): void {
  const plist = plistPath();
  if (!existsSync(plist)) return;
  try {
    execSync(`launchctl bootout gui/${uid()} "${plist}"`, { stdio: "ignore" });
  } catch {
    try {
      execSync(`launchctl unload "${plist}"`, { stdio: "ignore" });
    } catch {
      // already unloaded
    }
  }
}

function loadLaunchAgent(): void {
  const plist = plistPath();
  execSync(`launchctl bootstrap gui/${uid()} "${plist}"`, { stdio: "inherit" });
}

export function pipAutostartInstall(cliDir: string, workspace?: string): PipAutostartStatus {
  if (platform() !== "darwin") {
    throw new Error("Login autostart is macOS only.");
  }

  const pipRoot = findPipRoot(cliDir);
  const runScript = join(pipRoot, "run.sh");
  const pipMjs = join(pipRoot, "bin", "pip.mjs");
  if (!existsSync(runScript)) throw new Error(`Missing launcher: ${runScript}`);
  if (!existsSync(pipMjs)) throw new Error(`Missing launcher: ${pipMjs}`);
  chmodSync(runScript, 0o755);

  const ws = workspace ?? resolveWorkspace(resolve(cliDir, "../../.."));
  mkdirSync(dirname(envPath()), { recursive: true });
  writeFileSync(envPath(), `TANDEM_WORKSPACE=${ws}\n`, "utf8");
  const nodeBin = process.execPath;
  const launcher = launcherPath();
  writeFileSync(launcher, renderLauncher(nodeBin, pipMjs, ws), "utf8");
  chmodSync(launcher, 0o755);

  mkdirSync(join(homedir(), "Library", "LaunchAgents"), { recursive: true });
  unloadLaunchAgent();
  writeFileSync(plistPath(), renderPlist(launcher), "utf8");
  loadLaunchAgent();

  return pipAutostartStatus(cliDir);
}

export function pipAutostartUninstall(cliDir: string): void {
  unloadLaunchAgent();
  const plist = plistPath();
  if (existsSync(plist)) unlinkSync(plist);
  const env = envPath();
  if (existsSync(env)) unlinkSync(env);
  const launcher = launcherPath();
  if (existsSync(launcher)) unlinkSync(launcher);
  void cliDir;
}

export function pipAutostartUsage(): void {
  console.log(`Usage:
  tandem pip autostart install    Start Pip at login (macOS LaunchAgent)
  tandem pip autostart uninstall  Remove login autostart
  tandem pip autostart status     Show autostart state

Logs (when running via autostart):
  ${LOG_OUT}
  ${LOG_ERR}
`);
}
